spring.application.name=ai.chat.kz

spring.datasource.url=jdbc:postgresql://localhost:5432/ai.chat.kz
spring.datasource.username=whoami
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update